variable vpc_name {}
variable "vpc_cidr" {}
variable gw_name {}
variable "avail_zones" {}
variable "private_subnets" {}
variable "database_subnets" {}
variable "databse_subnet_name" {}
variable "private_subnet_name" {}
variable "public_subnets" {}
variable "public_subnet_name" {}
variable "cluster_name" {}