apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  namespace: jenkins
type: Opaque
data:
  config.json: ewogICAgImF1dGhzIjogewogICAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewogICAgICAgICJhdXRoIjogIllXSmhibTlpYlc5eWEyOXpNVEE2WVdJeFJrRXlQVXBCTXlRPSIKICAgICAgfQogICAgfQogIH0KICA=